name: Deploy Portfolio Static Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout main application repository (ulfbou.github.io)
        uses: actions/checkout@v4
        with:
          repository: ulfbou/ulfbou.github.io

      - name: (Debug) After Main Checkout
        run: |
          echo "--- (Debug) After Main Checkout (Current working directory) ---"
          pwd
          echo "--- (Debug) Contents of runner's workspace (after main checkout) ---"
          ls -R .
          echo "------------------------------------------------------------------"

      - name: Checkout Portfolio-Content repository
        uses: actions/checkout@v4
        with:
          repository: ulfbou/Portfolio-Content
          path: portfolio-content

      - name: (Debug) After Content Checkout
        run: |
          echo "--- (Debug) After Content Checkout (Current working directory) ---"
          pwd
          echo "--- (Debug) Contents of runner's workspace (after content checkout) ---"
          ls -R .
          echo "--------------------------------------------------------------------"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for Static Generator
        run: dotnet restore ./tools/PortfolioStaticGenerator

      - name: Build Static Generator
        run: dotnet build ./tools/PortfolioStaticGenerator --configuration Release --no-restore

      - name: (Debug) Before Static Generator Run
        run: |
          echo "--- (Debug) Before Static Generator Run (Current working directory) ---"
          pwd
          echo "--- (Debug) Contents of PortfolioStaticGenerator folder ---"
          ls -R ./tools/PortfolioStaticGenerator/
          echo "--- (Debug) Contents of portfolio-content folder ---"
          ls -R ./portfolio-content/
          echo "----------------------------------------------------"

      - name: Run Static Generator to create _site directory
        run: dotnet run --project ./tools/PortfolioStaticGenerator --configuration Release -- ContentRepoPath="${{ github.workspace }}/portfolio-content/" OutputDirectory="${{ github.workspace }}/_site/" BaseUrl="${{ steps.deployment.outputs.page_url }}"

      - name: (Debug) After Static Generator Run
        run: |
          echo "--- (Debug) After Static Generator Run (Current working directory) ---"
          pwd
          echo "--- (Debug) Contents of the workspace root (where _site should be) ---"
          ls -R ${{ github.workspace }}/_site || echo "WARNING: _site directory not found at workspace root!"
          echo "-----------------------------------------------------"

      - name: Copy generated _site content to root
        run: |
          echo "--- (Debug) Copying _site content to root (Current working directory: $(pwd)) ---"
          mkdir -p temp_root
          cp -R ${{ github.workspace }}/_site/. temp_root/
          echo "Contents of temp_root (after copying):"
          ls -R temp_root
          rm -rf ${{ github.workspace }}/_site 
          mv temp_root/* .
          echo "Contents of repository root (after final move):"
          ls -R .
          echo "-----------------------------------------"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4